{% set name = "hicolor-icon-theme" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://icon-theme.freedesktop.org/releases/{{ name }}-{{ version }}.tar.xz
  sha256: db0e50a80aa3bf64bb45cbca5cf9f75efd9348cf2ac690b907435238c3cf81d7

build:
  number: 0
  # it would be nice if this were noarch: generic because it just installs some files,
  # but we want them in $PREFIX on Unix and %LIBRARY_PREFIX% on Windows
  # noarch: generic

requirements:
  build:
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/share/icons/hicolor/index.theme  # [unix]
    - if not exist %PREFIX%\Library\share\icons\hicolor\index.theme exit 1  # [win]

about:
  home: https://wiki.freedesktop.org/www/Software/icon-theme/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Fallback theme for FreeDesktop.org icon themes'
  description: |
    This is the default fallback theme used by implementations of the icon
    theme specification.

    The specification is availible at:
    http://www.freedesktop.org/standards/icon-theme-spec/
  dev_url: https://gitlab.freedesktop.org/xdg/default-icon-theme

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
